name: Tests
on:
- push
- pull_request
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        BUILD_TARGET: [release]
      fail-fast: true
    outputs:
      release_built: ${{ steps.set-output.outputs.release_built }}
    steps:
    - uses: actions/checkout@v4
    - name: Build libraries in "${{ matrix.BUILD_TARGET }}" mode
      run: cargo build --profile ${{ matrix.BUILD_TARGET }}
    - name: Run tests in "${{ matrix.BUILD_TARGET }}" mode
      run: cargo test --profile ${{ matrix.BUILD_TARGET }}
